### ISSUE TITLE
Changelog is broken.

### ISSUE THREAD

**Issue by engiValk** [Aurum22/Eridani#5]
#### Brief description of the issue
Changelog isn't working right.
#### Steps to reproduce
Launch the server
#### Additional info:
https://cdn.discordapp.com/attachments/226498848611237889/271008526103609344/eJwFwdsNwyAMAMBdGADzMlTZBhFEoiY2wo76UXX33n3Nsy6zmUN1ygawn9J47VaUVx3dDuZx9TpPsY1vqKq1HXcnFfCvgOh8jiHHGJLPDkLxzhWPqaScAkYs8NCb-EN20jC_PwOJIsQ.png

**Comment by Aurum22** [comment]
Turns out I'm just dumb and the target changelog file was named improperly.
